name: semantic-release
on:
  push:
    branches:
      - main
    paths:
      - main.go
      - 'routeros/*.go'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    


jobs:
  semver:
    name: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx semantic-release
        ## Use PAT so this action triggers the release pipeline if it pushes a tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}