name: semantic-release
on:
  push:
    branches:
      - main
    paths:
      - main.go
      - 'routeros/*.go'
      - '.github/workflows/*.yml'

jobs:
  semver:
    name: semver
    runs-on: "ubuntu-latest"
    steps:
      - uses: codfish/semantic-release-action@v2