name: test
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        go: ["1.16"]
        os: [ubuntu-latest]
        # Test against RouterOS v7
        routeros:
          - "7.1"
        terraform:
          - "1.1.0"
        legacy_bgp_support: [true]
        include:
          - experimental: true
            go: 1.16
            os: ubuntu-latest
            routeros: "latest"
            legacy_bgp_support: false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Get dependencies
        run: | 
          go mod download

      - name: Build
        run: go build -v .

      - name: Run provider tests
        run: make testacc
        env:
          ROS_HOSTURL: https://127.0.0.1
          ROS_USERNAME: admin
          ROS_PASSWORD: ''
          ROS_INSECURE: true
          TF_ACC: 1
          LEGACY_BGP_SUPPORT: ${{ matrix.legacy_bgp_support }}

      - name: Run client tests
        run: make testclient
        env:
          ROS_HOSTURL: https://127.0.0.1
          ROS_USERNAME: admin
          ROS_PASSWORD: ''
          ROS_INSECURE: true
          TF_ACC: 1
          LEGACY_BGP_SUPPORT: ${{ matrix.legacy_bgp_support }}

    services:
      routeros:
        image: evilfreelancer/docker-routeros:${{ matrix.routeros }}
        ports:
          - 443:443
        volumes:
          - /dev/net/tun:/dev/net/tun
        options: >-
          --cap-add=NET_ADMIN
